language: node_js
node_js:
  - "13"
services:
  - docker
before_install:
  - make build_docker
  - docker images
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script:
  - make push_docker
