apiVersion: v1
kind: ReplicationController
metadata:
  name: samplenode
  namespace: node-dev
spec:
  replicas: 3
  selector:
    run: samplenode
  template:
    metadata:
      labels:
        run: samplenode
        name: samplenode
    spec:
      containers:
      - name: samplenode
        image: barteks/samplenode:latest
