apiVersion: v1
kind: Service
metadata:
  name: samplenode
  namespace: node-dev
  labels:
    run: samplenode
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: samplenode
  type: LoadBalancer
