apiVersion: v1
kind: ReplicationController
metadata:
  name: samplenode
  namespace: node-dev
spec:
  replicas: 3
  selector:
    run: samplenode
  template:
    metadata:
      labels:
        run: samplenode
    spec:
      containers:
      - name: samplenode
        image: barteks/samplenode:latest
        livenessProbe:
          httpGet:
            path: /healthCheck
            port: 80
          initialDelaySeconds: 15
        
