apiVersion: v1
kind: Service
metadata:
  name: samplenode
  namespace: node-dev
  labels:
    run: samplenode
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    run: samplenode
  type: LoadBalancer
